# Generated by Django 2.2 on 2019-12-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
